# Generated by Django 2.2 on 2019-07-26 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('birth_date', models.DateTimeField(auto_now_add=True)),
                ('country', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('register_date',),
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('FA', 'Facebook'), ('TW', 'Twitter'), ('GI', 'Github'), ('CO', 'Coretabs'), ('NO', 'None')], default='NO', max_length=2)),
                ('account_link', models.URLField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='accounts.Profile')),
            ],
        ),
    ]
